apiVersion: v1
kind: Service
metadata:
  name: {{ include "mavio-mcp.fullname" . }}
  labels: {{- include "mavio-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector: {{- include "mavio-mcp.selectorLabels" . | nindent 4 }}
